### ISSUE TITLE
Bug with scroll up

### ISSUE THREAD

**Issue by Psychodeus** [Schauweg/Smooth-Swapping#18]
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer
Mod version: 0.4.6

I'm using [Item Scroller](https://www.curseforge.com/minecraft/mc-mods/item-scroller) mod, and when I scroll wheel down the animation works, but when I scroll wheel up the animation doesn't work. Thanks.

**Comment by Schauweg** [comment]
Thanks for reporting, I already know this. This happens due to how the mod detects changes in the inventory. I'm currently rewriting the whole dectetion system and this should fix this issue.

**Comment by Schauweg** [comment]
#19 should be fixed with this update
