### ISSUE TITLE
[Bug] Visual artifacts when shift-clicking an item that gets removed instantly

### ISSUE THREAD

**Issue by CzechHek** [Schauweg/Smooth-Swapping#20]
I've encountered a really annoying purely visual bug, that is causing weird item counts to appear all over the screen when you shift-click an item of stack size >1 that gets removed instantly.
This issue is really common when you are working with Create mod, that enables you to move stacks of items at a time.
It is achievable even in vanilla with no other mods installed with the use of 2 hoppers under a double chest or command blocks.

I've recorded a video of this bug, so you can see how to reproduce it:
https://youtu.be/X69Z9gWJRPQ
https://youtu.be/HxGKjUr3phU
![image](https://user-images.githubusercontent.com/42714212/203832011-b2aec950-b506-4840-af37-eeab9cb0613f.png)

I feel like this is a pretty major issue, completely destroying the "smoothness" of this mod.

MC: 1.19.2
Fabric: 0.14.10
Smooth Swapping: 0.5

**Comment by CzechHek** [comment]
Nevermind, this can easily happen in vanilla mc as well. Basically: stack size of 2 shift clicked into chest with two hoppers under it.

Here is a vid: (you can see that if the item stack - chest stays there for some time (stack size 3+) then the glitch doesn't happen)
https://youtu.be/X69Z9gWJRPQ

**Comment by Schauweg** [comment]
also just released version 0.6 with a fix for this
