### ISSUE TITLE
Crash when shift clicking trade results from villagers

### ISSUE THREAD

**Issue by KJP12** [Schauweg/Smooth-Swapping#25]
## Steps to Reproduce
 - Trade with villagers.
   - Farmers with the cake trade tend to instantly crash.

Note: Botania's Black Hole Talisman and Manufactory Halo were both present in the inventory at the time, although neither were listening on cake at the time of crash.

## Corresponding code as decompiled with QuiltFlower from `-Dmixin.debug.export=true`
```java
    @MixinMerged(
        mixin = "schauweg.smoothswapping.mixin.ClickSlotPacketMixin",
        priority = 1000,
        sessionId = "6626809e-e2ac-47ef-956d-1d42b5e85319"
    )
    public void handler$epo005$onInit(CallbackInfo cbi) {
        SmoothSwapping.swaps.remove(this.field_12818);// 543
        if ((this.field_12815 == class_1713.field_7794 || this.field_12815 == class_1713.field_7791)// 545
            && this.field_29540.size() > 1
            && class_310.method_1551().field_1755 instanceof class_465) {
            assert class_310.method_1551().field_1724 != null;// 546

            class_746 class_746 = class_310.method_1551().field_1724;// 548
            class_1703 class_1703 = class_746.field_7512;// 549
            class_1735 class_1735 = class_1703.method_7611(this.field_12818);// 550
            if (this.field_12815 == class_1713.field_7794 && !class_1735.method_32754(class_746)) {// 552
                class_1799 class_1799 = (class_1799)this.field_29540.get(this.field_12818);// 554
                class_1799 class_1799x = (class_1799)SmoothSwapping.oldStacks.get(this.field_12818);// 555
                if (class_1799.method_7947() - class_1799x.method_7947() <= 0) {// 558
                    SmoothSwapping.clickSwapStack = this.field_12818;// 559
                }
            } else if (this.field_12815 == class_1713.field_7791) {// 562
```

This seems to be related to this line: https://github.com/Schauweg/Smooth-Swapping/blob/ab5ce07b16d683e4e6000892b33f352204ad62dd/src/main/java/schauweg/smoothswapping/mixin/ClickSlotPacketMixin.java#L58

*Got the wrong line initially*

## Crash Report
https://gist.github.com/KJP12/6eb118aed6b380db100a164528170746

**Comment by KJP12** [comment]
Reproduced at 4fe1d879a06109c506ac9ea4207697469d5bdcb3, with suspicious stew. This seems to be due to the inventory being filled up while trading, causing the crash.

Note that I'm building against an older revision because the head of the master and testing branches are messy with left overs from Cloth Config... which I'm not sure how it got left behind.

**Comment by Schauweg** [comment]
Thanks for telling me about the issues with cloth config stuff, I've totally missed that for some reason. I'll try to push the proper file asap. Maybe you csn try building again and see if the problem still occures. 

I'm kinda a git noob so bare with me 😅

**Comment by KJP12** [comment]
It indeed makes it possible to build locally as is, although it doesn't fix the trade filling up the inventory and immediately crashing issue.

I think it might be possible to use last clicked slot as a fallback for if there's none that has seen a decrement and thus a change.

**Comment by KJP12** [comment]
Well, a quick null check made the items from the trades come from the emerald rather than the output slot, which is definitely not correct; lets invert that to is null or if?

**Comment by KJP12** [comment]
Hm, the crafting table is claiming that the bread is coming from the input wheat

**Comment by KJP12** [comment]
However, that seems unrelated to the quick NPE patch; just needs better detection of input vs. output, or matching items?
