### ISSUE TITLE
Recipe book and villager trade menu aren't smooth

### ISSUE THREAD

**Issue by il-av** [Schauweg/Smooth-Swapping#3]
When you use the recipe book to add items to the crafting grid and when you click on trades in the villager gui it doesn't animate smoothly.

**Comment by Schauweg** [comment]
Yes, I already know this, but the problem is that it get's handled serverside which items go into the crafting/treading slot so it's not that easy to figure out which Items to move.

**Comment by Schauweg** [comment]
After of a year I finally found the motivation to do this, though the trading screen is a bit wonky still #19
