### ISSUE TITLE
Client crash while crafting in travelers backpack

### ISSUE THREAD

**Issue by LNatit** [Schauweg/Smooth-Swapping#31]
**Describe the bug**
When I was crafting in travelers backpack on sever, my game crashed.
I tied to remove some mods to locate the reason, and confirmed that SmoothSwapping caused the crash.

**To Reproduce**
The crash seemed to happen each time when I craft a stick or spruce stair.

**Required informations (please complete the following information):**
- Mod version: 1.19.2-1.0.0
- Mod Loader: [Forge]

**Additional context**
Here is the detailed crash info: 
[错误报告-2022-12-1_20.57.56.zip](https://github.com/Schauweg/Smooth-Swapping/files/10137374/-2022-12-1_20.57.56.zip)

**Comment by Schauweg** [comment]
Sorry I don't maintain the forge port myself, maybe try reporting the issue here on the [Forge Port](https://github.com/baguchan/Smooth-Swapping-Forge) repo
