### ISSUE TITLE
Crashes Game

### ISSUE THREAD

**Issue by GhostGekko** [Schauweg/Smooth-Swapping#33]
Crash can occur when creating a new creative world, or moving an item from the creative tab.

This is on Fabric 0.14.11 with Fabric API 0.67.0+1.18.12.

Here is the crash information:

[crash-2022-12-18_22.50.44-client.txt](https://github.com/Schauweg/Smooth-Swapping/files/10256562/crash-2022-12-18_22.50.44-client.txt)

[latest.log](https://github.com/Schauweg/Smooth-Swapping/files/10256559/latest.log)

[Screenshot 2022-12-18 225447](https://user-images.githubusercontent.com/62355150/208365626-b69bd58d-a1fa-4f36-867f-a80694a3e633.png)

**Comment by Schauweg** [comment]
Do you have ModMenu installed?
