### ISSUE TITLE
Crashes the game when shift+right clicking on 2x2 crafting grid

### ISSUE THREAD

**Issue by DeckerExpert** [Schauweg/Smooth-Swapping#36]
Title says it all; the mod crashes the game when shift and right clicking on the results of crafting on the survival crafting 2x2 grid. Haven't tested on a 3x3 crafting grid, but I'm pretty sure it will do the same thing.

Here's the crash report
[crash-2022-12-30_10.40.51-client.txt](https://github.com/Schauweg/Smooth-Swapping/files/10323018/crash-2022-12-30_10.40.51-client.txt)

**Comment by RobertasJ** [comment]
Same isssue on skylore.

**Comment by Schauweg** [comment]
Can't reproduce the crash, sorry
