### ISSUE TITLE
Crashes Game When Opening World

### ISSUE THREAD

**Issue by BraxM10** [Schauweg/Smooth-Swapping#38]
The game opens like normal but whenever i create a new world or try to load into an existing world my game crashes.

Other mods i had installed: fabric api, sodium, lithium, phosphor, iris
Shader: sildurs vibrant shaders (high)
Resourcepack: vanilla tweaks

**Comment by onyxagata** [comment]
I experienced this issue with Smooth Swapping 0.6

Downgrading to version 0.5 fixed my issue
