### ISSUE TITLE
Crash with INMIS

### ISSUE THREAD

**Issue by AndyXTJ** [Schauweg/Smooth-Swapping#4]
Hey, I'm playing fabric 1.17.1, and this mod crashed when I used the keyboard (3 specifically) to move a item from my inventory to the chest, it seems like INMIS could be involved though I wasn't exactly using the backpack atm. It was a normal minecraft chest, not a modded one.

Here's the head crash report file
[smooth crash.txt](https://github.com/Schauweg/Smooth-Swapping/files/7269749/smooth.crash.txt)

**Comment by AndyXTJ** [comment]
I was able to replicate the bug. It seems when you shift click a INMIS backpack into a container, it crashes.

**Comment by Schauweg** [comment]
Okay, thank you for the bug report and testing, sadly I'm currently not able to work on my mod due to health problems. 
I'm not sure when I'm gonna be able to work on it again, but I'll as soon as I have the time to do so.

**Comment by SukiDoodle** [comment]
Any chance of this being fixed yet....? Hope you are or feel better soon \o/

**Comment by Schauweg** [comment]
Thanks for the kind words! I have no clue whats going on with this crash. I tried the same with another backpack mod for fabric and it worked without any issues...

**Comment by Schauweg** [comment]
Workaround for, hopefully will come up with a proper fix later. Thanks again @MagicSweet-dev!
