### ISSUE TITLE
Mod isn't showing up in my game.

### ISSUE THREAD

**Issue by mshailz** [Schauweg/Smooth-Swapping#50]
I'm on the latest release of this mod for Fabric, using fabric loader 0.14.19-1.19.4, Fabric API version fabric-api-0.78.0+1.19.4 with Architectury API version architectury-8.1.80-fabric. I'm also using the latest version of ModMenu 6.2.2.

Mod isn't showing up in Mod Menu, nor in any of my settings. Is there something I could possibly be missing? I did not get any mod compatibility errors either.

**Comment by Schauweg** [comment]
I downloaded all the mods with the same versions and for me it shows up. Maybe did you download the Forge mod by accident?

**Comment by mshailz** [comment]
> I downloaded all the mods with the same versions and for me it shows up. Maybe did you download the Forge mod by accident?

I probably did and missed it. I downloaded a earlier version of Smooth Swapping and it works. I'll try again and check in afterwards.

**Comment by mshailz** [comment]
> 

It works, I was in creative. I would love to see a creative version of this. Keep up the great work!
