### ISSUE TITLE
Inmis backpack mod crashing

### ISSUE THREAD

**Issue by kyber-6** [Schauweg/Smooth-Swapping#56]
Using the Inmis backpacks mod with Smooth Swapping causes crashes when shift-clicking items into or from the backpack.

[crash-2023-06-09_23.32.01-client.txt](https://github.com/Schauweg/Smooth-Swapping/files/11714326/crash-2023-06-09_23.32.01-client.txt)

**Comment by Schauweg** [comment]
Please update to version 0.9.2 and see if that fixes it

**Comment by kyber-6** [comment]
Thanks for the quick response, I will re-open this issue if it persists.
