### ISSUE TITLE
One of the downloads is mislabelled on Modrinth

### ISSUE THREAD

**Issue by billyp673** [Schauweg/Smooth-Swapping#67]
If you filter by version [1.19.4], the top download is the 1.20 version, which breaks compatibility with PolyMC's automatic downloader. In other words, the 1.20 download is mislabelled as 1.19.4.
<img width="558" alt="mislabelled" src="https://github.com/Schauweg/Smooth-Swapping/assets/64395292/292fbcb0-8946-4e6f-aafc-57f5ae26845b">

**Comment by Schauweg** [comment]
thanks for reporting, I fixed that
