### ISSUE TITLE
Add 1.20.1 compatibility tag

### ISSUE THREAD

**Issue by IntM4rco** [Schauweg/Smooth-Swapping#72]
<img width="1253" alt="Screenshot 2023-08-14 alle 18 01 44" src="https://github.com/Schauweg/Smooth-Swapping/assets/124934175/fe0e6362-604d-4c8d-886c-082dbfc43ff9">

**Comment by SpektacleFR** [comment]
But does the mod still work for 1.20.1?

**Comment by Schauweg** [comment]
new version is compatible with all version of 1.20 so far and tagged as so on modrinth
