### ISSUE TITLE
Game sometimes crashes when shift + click

### ISSUE THREAD

**Issue by Binekrasik** [Schauweg/Smooth-Swapping#74]
Recently I was playing my survival world, nothing special, but when I shift + clicked in furnace to add coal the game crashed. Here's my crash report.
 
https://pastebin.com/X69iWQsQ

**Comment by saeftygit** [comment]
Can confirm this happens to me also. Looks its caused by an exception loop in ItemRendererMixin
```java
try {
     doSwap(stack, matrices, model, x, y, cbi);
} catch (Exception e) {
    SwapUtil.reset(); // Here is where loop is probably caused, maybe just default to normal swap without smoothing as temp fix
}
```

**Comment by papamaionise** [comment]
same issue

**Comment by Schauweg** [comment]
> Can confirm this happens to me also. Looks its caused by an exception loop in ItemRendererMixin

This was my attempt to make it into a normal swap, but I guess it didn't work, but I have a hopefully more robust solution now which should work better
