### ISSUE TITLE
Crashing when using grindstone

### ISSUE THREAD

**Issue by TBNR-DARKNIGHT** [Schauweg/Smooth-Swapping#78]
Game crashes when using grindstone to disenchant tools when shift left-clicking the disenchanted tool back into the inventory.
[crash-2023-10-05_23.15.25-client.txt](https://github.com/Schauweg/Smooth-Swapping/files/12820155/crash-2023-10-05_23.15.25-client.txt)

**Comment by Schauweg** [comment]
This should be fixed now with the lastest release
