### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kyber-6** [Schauweg/Smooth-Swapping#80]
Report from someone playing our Fantasy MC modpack

Mod version: smoothswapping-0.9.2-1.20-fabric
Minecraft version: 1.20.1
Fabric version: 0.14.22

> All I did was click a wooden axe into a furnace
[crash-2023-10-12_07.01.51-client.txt](https://github.com/Schauweg/Smooth-Swapping/files/12886693/crash-2023-10-12_07.01.51-client.txt)

**Comment by Schauweg** [comment]
This should be fixed now thank you for your report
