### ISSUE TITLE
Mod Menu Settings Game Crash 1.20.2

### ISSUE THREAD

**Issue by nco2k** [Schauweg/Smooth-Swapping#84]
opening up mod menu and clicking on the settings button of this mod makes the game crash with following error:

- The game crashed whilst mouseclicked event handler
- Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_1735.method_48931(net.minecraft.class_1799)'
- Exit Code: -1073740791

im using the latest files:

- fabric-api-0.90.7+1.20.2.jar
- modmenu-8.0.0.jar
- smoothswapping-0.9.2-1.20.1-fabric.jar

**Comment by Schauweg** [comment]
Thanks for the report, thats really strange, it works in my dev environment but doesn't work when build. I have to look into this.

**Comment by Schauweg** [comment]
I've uploaded a new version, which hopefully should fix the issue

**Comment by nco2k** [comment]
it sure does. :)
