### ISSUE TITLE
Slight rewrites & typo fixes for the README.MD file.

### ISSUE THREAD

**Issue by june-hibiscus** [Schauweg/Smooth-Swapping#85]
[README.MD](https://github.com/Schauweg/Smooth-Swapping/files/13256831/README.MD)

Note:
The README.MD did say that the mod was available _since 1.19.4_, although the Modrinth page also displays available downloads for 1.17.4 - I cannot tell if that is meant to mean "Been in development since 1.19.4" or if it a mistake made while writing.

Might want to keep it in mind if it indeed is a mistake!

Apologies I forgot that I can just PR this...

**Comment by Schauweg** [comment]
The Forge version is available since 1.19.4, maybe I should word it more correctly

**Comment by june-hibiscus** [comment]
> The Forge version is available since 1.19.4, maybe I should word it more correctly

Got it
